#!/usr/bin/perl
#
# Remove unwanted stuff from the VMware tools installation
# First untar the distribution into this directory
# Run this script
# tar czvf VMwareTools.tgz vmware-tools-distrib

$base="vmware-tools-distrib";

@kernels = `find $base/lib/modules/binary/ -mindepth 1 -maxdepth 1 -print`;

# Remove everything except for 64 bit RHEL 5+ and Ubuntu 9+ kernels
# This takes it from 288M to 104M 

foreach $kernel (grep(!/-x86_64.*?-(RHEL[5-9]|Ubuntu(9|1[0-9]))/,@kernels)) {
    `rm -rf $kernel`
}

# Remove all the 32 bit stuff
# Takes it from 104M to 66M

`rm -rf $base/lib/lib32/*`;
`rm -rf $base/lib/bin32/*`;
`rm -rf $base/lib/sbin32/*`;
`rm -rf $base/lib/plugins32`;

`touch $base/lib/bin32/vmware-user-suid-wrapper`;
`touch $base/lib/sbin32/vmware-hgfsmounter`;

# Remove SDK fluff

`rm -rf $base/GuestSDK`;

# vim: ts=8 sw=4 sts=4:
