# This fragment specifies the bare minimum packages for a production machine
#
@base
@core
@console-internet
@directory-client
@network-file-system-client
@system-admin-tools
kexec-tools
fipscheck
screen
lynx
git
nss-mdns
pam_ldap
nss-pam-ldapd
ruby
irb
yum-plugin-priorities
# These are for building new rubies (taken from rvm notes)
gcc-c++
patch
readline
readline-devel
zlib
zlib-devel
libyaml-devel
libffi-devel
openssl-devel
